receivers:
  otlp:
    protocols:
      grpc:
      http:
#        cors_allowed_origins:
#        - "*"

processors:
  batch:

exporters:
#  azuremonitor:
#    instrumentation_key:
#    endpoint: https://dc.services.visualstudio.com/v2/track
#  elasticsearch:
#    endpoints: [http://elasticsearch:9200]
#    tls:
#      insecure: true
  jaeger:
    endpoint: jaeger:14250
    tls:
      insecure: true
  logging:
    logLevel: info

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging, jaeger]
    logs:
      receivers: [otlp]
      processors: [batch]
#      exporters: [logging, elasticsearch]
      exporters: [logging]
      