receivers:
  otlp:
    protocols:
      grpc:
      http:

processors:
  batch:

exporters:
  azuremonitor:
    instrumentation_key: "${AZ_INSTRUMENTATION_KEY}"
# ISSUE: Client used does not support open source version of Elastic.
#  elasticsearch:
#    endpoints: [http://elasticsearch:9200]
#    tls:
#      insecure: true
  jaeger:
    endpoint: jaeger:14250
    tls:
      insecure: true
  logging:
    logLevel: info

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging, jaeger, azuremonitor]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging, azuremonitor]
#      exporters: [logging, elasticsearch, azuremonitor]

