receivers:
  otlp:
    protocols:
      grpc:
      http:
#        cors_allowed_origins:
#        - "*"

processors:
  batch:

exporters:
  azuremonitor:
    instrumentation_key: "${AZ_INSTRUMENTATION_KEY}"
#    endpoint: "{$AZ_ENDPOINT}"
#  elasticsearch:
#    endpoints: [http://elasticsearch:9200]
#    tls:
#      insecure: true
  jaeger:
    endpoint: jaeger:14250
    tls:
      insecure: true
  logging:
    logLevel: info

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
#      exporters: [logging, jaeger]
      exporters: [logging, jaeger, azuremonitor]
    logs:
      receivers: [otlp]
      processors: [batch]
#      exporters: [logging, elasticsearch]
      exporters: [logging, azuremonitor]
#      exporters: [logging]
